name: Checkout
on: [push]

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -a

      - name: Checkout
        run: |
          git init
          git config --global init.defaultBranch main
          git remote add origin "https://github.com:${{secrets.GITHUB_TOKEN}}/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main

      - name: List Files After
        run: ls -a
