name: Shell Commands
on: [push]

defaults:
  run:
    shell: bash

jobs:
  display-working-dir:
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE

      - name: Change Working Directory
        working-directory: /home/runner
        run: pwd
